### ISSUE TITLE
Text color does not work completely

### ISSUE THREAD

**Issue by VladC12** [Yegiyan/Bisqwit-Terminal-Theme-for-Visual-Studio#1]
I attached a picture:
![SharedScreenshot](https://user-images.githubusercontent.com/34303919/77260508-1a912900-6c91-11ea-8452-78306a21d1da.jpg)

**Comment by Yegiyan** [comment]
Changed 'Text Editor -> Plain Text -> Background' to #FF000000
The issue should be fixed now.
